#!/bin/bash
# QUICK START GUIDE - Production RAG Pipeline Setup

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🚀 ELEVANT DIGITAL - PRODUCTION RAG SETUP GUIDE           ║"
echo "║  (Preventing Gemini 429 RESOURCE_EXHAUSTED Errors)        ║"
echo "╚════════════════════════════════════════════════════════════╝"

echo ""
echo "📋 SETUP CHECKLIST:"
echo ""

echo "1️⃣  Update .env with environment variables"
echo "   Required:"
echo "   - GEMINI_API_KEY=your-key"
echo "   - QDRANT_URL=your-url"
echo "   - QDRANT_API_KEY=your-key"
echo "   Optional (for resumable ingestion):"
echo "   - MONGODB_URI=mongodb+srv://..."
echo "   "
echo "   Reference: .env.example"
echo ""

echo "2️⃣  Install dependencies"
echo "   $ npm install"
echo ""

echo "3️⃣  Create Qdrant collection"
echo "   $ node embedding.js"
echo "   ✓ Creates 'books' collection with 3072-dim vectors"
echo ""

echo "4️⃣  Start the server"
echo "   $ npm start"
echo "   ✓ Server runs on port 3000 (configurable)"
echo ""

echo "5️⃣  Ingest your first book"
echo "   $ curl -X POST http://localhost:3000/ingest \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"text\":\"Your book content...\"}'"
echo "   "
echo "   Response: {\"success\": true, \"jobId\": \"...\"}"
echo ""

echo "6️⃣  Monitor ingestion progress"
echo "   $ curl http://localhost:3000/ingest/{jobId}"
echo "   "
echo "   Logs show:"
echo "   - Batch progress: 📦 [BATCH 1/50]"
echo "   - Rate limiting: ⏳ [RATE_LIMIT]"
echo "   - Quota errors: ⚠️  [429 QUOTA]"
echo "   - Completion: ✓ [INGESTION COMPLETED]"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 KEY FEATURES:"
echo "   ✓ Rate limiting: 80 requests/min (safe margin)"
echo "   ✓ Exponential backoff: Auto-retry with jitter"
echo "   ✓ Batch processing: 10 chunks/batch (configurable)"
echo "   ✓ Duplicate detection: Skip already-embedded chunks"
echo "   ✓ Resumable ingestion: MongoDB tracks progress"
echo "   ✓ Structured logging: Detailed metrics & ETA"
echo ""

echo "⚙️  CONFIGURATION:"
echo "   Environment Variables (optional, defaults shown):"
echo "   - EMBED_REQUESTS_PER_MINUTE=80"
echo "   - EMBED_BATCH_SIZE=10"
echo "   - EMBED_MAX_RETRIES=5"
echo "   - MONGODB_URI=(optional)"
echo "   - PORT=3000"
echo ""

echo "📚 DOCUMENTATION:"
echo "   See RATE_LIMITING_GUIDE.md for:"
echo "   - How rate limiting prevents 429 errors"
echo "   - Tuning for different quota levels"
echo "   - Performance optimization"
echo "   - Troubleshooting"
echo ""

echo "🔍 MONITORING:"
echo "   Watch server logs for:"
echo "   ⏳ Rate limit messages (normal)"
echo "   ⚠️  429 errors with backoff (expected under load)"
echo "   📦 Batch progress updates"
echo "   ✓ Final completion report with metrics"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ You're ready to safely ingest large books without hitting"
echo "   Gemini API rate limits! 🎉"
